setup-only-experiment: local 'bits' referenced befor assignment
Now I think we've finally arrived at the bug which prompted this
experiment. Bits is failing because local var is being used instead of
global.


```
B:\code\apt\wildlands>python apt-setup.py %temp%\apt-%random% x86_64
Root: C:\Users\Matt\AppData\Local\Temp\apt-20718
Bits: x86_64
Root dir not found, creating C:\Users\Matt\AppData\Local\Temp\apt-20718
creating C:\Users\Matt\AppData\Local\Temp\apt-20718/etc/setup/
creating C:\Users\Matt\AppData\Local\Temp\apt-20718/etc/setup//installed.db
getting C:\Users\Matt\AppData\Local\Temp\apt-20718/etc/setup//setup.ini
Traceback (most recent call last):
  File "apt-setup.py", line 153, in <module>
    setup(root)
  File "apt-setup.py", line 24, in setup
    update()
  File "apt-setup.py", line 53, in update
    filename =  '%s/%s'%(bits, 'setup.ini')
UnboundLocalError: local variable 'bits' referenced before assignment
```

--HG--
branch : bit-ness