--bits with Setup is required and has no default
~~~
B:\code\apt>apt setup
Couldn't open d:/temp/apt-mar31/etc/setup//setup.rc, setting empty
error: `--bits` is required parameter for Setup

*** CPU Architecture not defined. Please use `--bits [32 | 64]`
~~~

--HG--
branch : bit-ness