Experiment: stip down to only `apt setup`
Debugging is proving too hard for me. Create a new script that uses
*only* the pieces necessary to complete `apt setup` with bitness.

Current blocking bug:

```
B:\code\apt\wildlands>python apt-setup.py %temp%\apt-%random% x86_64
Traceback (most recent call last):
  File "apt-setup.py", line 142, in <module>
    cache_dir = get_cache_dir()
  File "apt-setup.py", line 104, in get_cache_dir
    except knownpaths.PathNotFoundException:
NameError: global name 'knownpaths' is not defined
```

This is strange, because I don't see knownpaths defined anywhere at
all,so it should be broken in apt.py too?

--HG--
branch : bit-ness