Emit more meaningful message when package not found in setup ini dict
Found with `apt requires tinyows`, which just happens to require another
package which doesn't exist. So the package definition for tinyows is
broken.

The open question is, how will we handle it? It's okay for `requires()`
to just quit, but `get_all_dependencies()` etc. should be able to carry
on.

Before fix:

```
B:\code\apt>apt requires tinyows
----- "tinyows" requires the following directly to work -----
apache
msvcrt
iconv
fcgi
libxml2
regex
----- Sub dependencies are ----

KeyError: 'regex'
```

After fix:

```
B:\code\apt>apt requires tinyows
----- "tinyows" requires the following directly to work -----
apache
msvcrt
iconv
fcgi
libxml2
regex
----- Sub dependencies are ----

KeyError: '*** Package "regex" not found in distribution "curr"'
```