fix: debug warning was missing package name
```
*** Error:
Traceback (most recent call last):
  File "apt.py", line 1951, in <module>
    dists = parse_setup_ini(setup_ini)
  File "apt.py", line 1557, in parse_setup_ini
    d = set_extended_info(d)
  File "apt.py", line 1461, in set_extended_info
    print "\n*** Warning: '%s' is missing %s entry in setup.ini. This might cause problems.\n" % (p,
 e)
NameError: global name 'p' is not defined
```