Step towards allowing any of '32,64,x32,x64,x86,x86_86' for --arch
Still have something out of order though. I think it's because of using 'bits' one time and 'arch' another, and getting mixed up about precedence.

```
B:\code\apt>apt --arch x32 setup
CPU Architecture: x86
Couldn't open d:/temp/aptxx/etc/setup//setup.rc, setting empty
getting d:/temp/aptxx/etc/setup//setup.ini

UnboundLocalError: local variable 'bits' referenced before assignment
```

--HG--
branch : bit-ness